"""empty message

Revision ID: 44c2aee5f1bf
Revises: c202ba5ffc28
Create Date: 2018-03-19 18:22:49.026309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c2aee5f1bf'
down_revision = 'c202ba5ffc28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'application_list', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application_list', type_='unique')
    # ### end Alembic commands ###
