"""empty message

Revision ID: 51d9ea7d8aed
Revises: 44c2aee5f1bf
Create Date: 2018-03-20 16:59:32.649280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d9ea7d8aed'
down_revision = '44c2aee5f1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('app_list_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=225), nullable=True),
    sa.Column('api_key', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('node_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    # ### end Alembic commands ###
