"""empty message

Revision ID: a37b8b44feab
Revises: 68007ba788ef
Create Date: 2018-03-19 02:08:07.370721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37b8b44feab'
down_revision = '68007ba788ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('group', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'group')
    # ### end Alembic commands ###
